### ISSUE TITLE
not work. os: fedora 37

### ISSUE THREAD

**Issue by wencan** [morrownr/8821cu-20210916#82]
OS: Fedora Linux 37 (Workstation Edition) x86_64   
Kernel: 6.2.9-200.fc37.x86_64  
chipset: Bus 003 Device 002: ID 0bda:c811 Realtek Semiconductor Corp. 802.11ac NIC  

dmesg:
[dmesg.txt](https://github.com/morrownr/8821cu-20210916/files/11185589/dmesg.txt)

**Comment by morrownr** [comment]
Hi @wencan 

Since you have secure boot active, the problem is likely related to that. I have instructions in the README.md and FAQ.md related to secure boot. You can probably get by with the following at this point:

Install `openssl`

Rerun `install-driver.sh` per the instructions in Installation Step 8.
